nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']  # Your React app origin
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: []
        max_age: 3600
        allow_credentials: false

    paths:
        '^/api/':   # Only apply CORS to /api routes
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: false