version: '3.9'

services:
  php:
    image: php:8.1-fpm-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini # Optional: Custom php.ini
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=dev # Or prod for production
      - DATABASE_URL=mysql://db_user:db_password@database:3306/db_name?serverVersion=8.0&charset=utf8mb4 # MySQL connection string
      # Add other environment variables as needed

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0 # Use a specific MySQL version
    environment:
      - MYSQL_ROOT_PASSWORD=root_password # Set the root password (important!)
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    volumes:
      - db_data:/var/lib/mysql # Persist database data
    ports:
      - "3306:3306" # Expose MySQL port (optional)

volumes:
  db_data: