services:
  php:
    #image: php:8.2-fpm-alpine
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini # Optional: Custom php.ini
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=dev # Or prod for production
      - DATABASE_URL=mysql://root:rootpw@database:3306/assignment
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  nginx:
    #image: nginx:latest
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

  database:
    image: mysql:8.0 # Use a specific MySQL version
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw # Set the root password (important!)
      - MYSQL_DATABASE=assignment
    volumes:
      - db_data:/var/lib/mysql # Persist database data
    ports:
      - "3306:3306" # Expose MySQL port (optional)
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  react:
    build:
      context: ../frontend/
    ports:
      - "3000:80"
    depends_on:
      - php
      - database
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge